import mongoose from 'mongoose';
import dotenv from 'dotenv';
dotenv.config();

const schoolId = '6a283e8937aa6f5da42b130c'; // arya@gmail.com

const seedCandidates = [
  {
    ownerSchoolId: schoolId,
    schoolId: schoolId,
    source: 'SCHOOL_LINK',
    fullName: 'Neha Sharma',
    mobile: '9829012345',
    email: 'neha.sharma@example.com',
    gender: 'female',
    dob: new Date('1996-05-14'),
    address: 'Plot 42, Sector 5, Mansarovar',
    city: 'Jaipur',
    state: 'Rajasthan',
    area: 'Mansarovar',
    position: 'TGT Mathematics',
    qualifications: ['B.Sc', 'M.Sc', 'B.Ed'],
    subjects: ['Mathematics'],
    classesCanTeach: ['Class 6', 'Class 7', 'Class 8', 'Class 9', 'Class 10'],
    experienceYears: 4,
    expectedSalary: 28000,
    bEd: true,
    mEd: false,
    status: 'shortlisted',
    isDeleted: false,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
  },
  {
    ownerSchoolId: schoolId,
    schoolId: schoolId,
    source: 'ADMIN',
    fullName: 'Rahul Verma',
    mobile: '9829098765',
    email: 'rahul.verma@example.com',
    gender: 'male',
    dob: new Date('1993-08-22'),
    address: 'Near Queens Road, Vaishali Nagar',
    city: 'Jaipur',
    state: 'Rajasthan',
    area: 'Vaishali Nagar',
    position: 'PGT Physics',
    qualifications: ['B.Sc', 'M.Sc Physics', 'B.Ed'],
    subjects: ['Physics', 'Science'],
    classesCanTeach: ['Class 9', 'Class 10', 'Class 11', 'Class 12'],
    experienceYears: 6,
    expectedSalary: 38000,
    bEd: true,
    mEd: false,
    status: 'interview_scheduled',
    isDeleted: false,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 days ago
  },
  {
    ownerSchoolId: schoolId,
    schoolId: schoolId,
    source: 'SCHOOL_LINK',
    fullName: 'Pooja Choudhary',
    mobile: '9829145678',
    email: 'pooja.choudhary@example.com',
    gender: 'female',
    dob: new Date('1998-11-03'),
    address: 'Vikas Colony, Bagru',
    city: 'Jaipur',
    state: 'Rajasthan',
    area: 'Bagru',
    position: 'PRT English & EVS',
    qualifications: ['BA English Hons', 'B.Ed', 'CTET'],
    subjects: ['English', 'Social Science'],
    classesCanTeach: ['Class 1', 'Class 2', 'Class 3', 'Class 4', 'Class 5'],
    experienceYears: 2,
    expectedSalary: 22000,
    bEd: true,
    mEd: false,
    status: 'new',
    isDeleted: false,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
  },
  {
    ownerSchoolId: schoolId,
    schoolId: schoolId,
    source: 'ADMIN',
    fullName: 'Amit Kumar Meena',
    mobile: '9829234567',
    email: 'amit.meena@example.com',
    gender: 'male',
    dob: new Date('1997-02-18'),
    address: 'Airport Road, Sanganer',
    city: 'Jaipur',
    state: 'Rajasthan',
    area: 'Sanganer',
    position: 'Computer & IT Teacher',
    qualifications: ['BCA', 'MCA'],
    subjects: ['Computer Science'],
    classesCanTeach: ['Class 5', 'Class 6', 'Class 7', 'Class 8', 'Class 9', 'Class 10'],
    experienceYears: 3,
    expectedSalary: 25000,
    bEd: false,
    mEd: false,
    status: 'new',
    isDeleted: false,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    ownerSchoolId: schoolId,
    schoolId: schoolId,
    source: 'ADMIN',
    fullName: 'Sunita Shekhawat',
    mobile: '9829345678',
    email: 'sunita.shekhawat@example.com',
    gender: 'female',
    dob: new Date('1994-06-30'),
    address: 'Model Town, Malviya Nagar',
    city: 'Jaipur',
    state: 'Rajasthan',
    area: 'Malviya Nagar',
    position: 'TGT Hindi & Sanskrit',
    qualifications: ['MA Hindi', 'B.Ed', 'M.Ed'],
    subjects: ['Hindi', 'Sanskrit'],
    classesCanTeach: ['Class 6', 'Class 7', 'Class 8', 'Class 9', 'Class 10'],
    experienceYears: 5,
    expectedSalary: 32000,
    bEd: true,
    mEd: true,
    status: 'hired',
    isDeleted: false,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
  },
  {
    ownerSchoolId: schoolId,
    schoolId: schoolId,
    source: 'SCHOOL_LINK',
    fullName: 'Vikas Saini',
    mobile: '9829456789',
    email: 'vikas.saini@example.com',
    gender: 'male',
    dob: new Date('1997-09-12'),
    address: 'RIICO Industrial Area, Sitapura',
    city: 'Jaipur',
    state: 'Rajasthan',
    area: 'Sitapura',
    position: 'Sports & PE Coach',
    qualifications: ['B.P.Ed', 'BA Physical Ed'],
    subjects: ['Physical Education'],
    classesCanTeach: ['Class 6', 'Class 7', 'Class 8', 'Class 9', 'Class 10', 'Class 11', 'Class 12'],
    experienceYears: 3,
    expectedSalary: 26000,
    bEd: false,
    mEd: false,
    status: 'shortlisted',
    isDeleted: false,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    ownerSchoolId: schoolId,
    schoolId: schoolId,
    source: 'SCHOOL_LINK',
    fullName: 'Anjali Saxena',
    mobile: '9829567890',
    email: 'anjali.saxena@example.com',
    gender: 'female',
    dob: new Date('2000-01-25'),
    address: 'Mahal Road, Jagatpura',
    city: 'Jaipur',
    state: 'Rajasthan',
    area: 'Jagatpura',
    position: 'Pre-Primary / NTT Educator',
    qualifications: ['NTT', 'BA'],
    subjects: ['English', 'Drawing'],
    classesCanTeach: ['Playgroup', 'Nursery', 'KG', 'Prep'],
    experienceYears: 1,
    expectedSalary: 18000,
    bEd: false,
    mEd: false,
    status: 'new',
    isDeleted: false,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  },
  {
    ownerSchoolId: schoolId,
    schoolId: schoolId,
    source: 'ADMIN',
    fullName: 'Rakesh Rathore',
    mobile: '9829678901',
    email: 'rakesh.rathore@example.com',
    gender: 'male',
    dob: new Date('2001-07-19'),
    address: 'DCM, Ajmer Road',
    city: 'Jaipur',
    state: 'Rajasthan',
    area: 'Ajmer Road',
    position: 'TGT Social Science',
    qualifications: ['BA History', 'B.Ed'],
    subjects: ['Social Science', 'History'],
    classesCanTeach: ['Class 6', 'Class 7', 'Class 8'],
    experienceYears: 0,
    expectedSalary: 20000,
    bEd: true,
    mEd: false,
    status: 'new',
    isDeleted: false,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  const Candidate = mongoose.model('Candidate', new mongoose.Schema({}, { strict: false }));
  
  // Clean up any existing test records for this school first
  const deleted = await Candidate.deleteMany({ ownerSchoolId: schoolId });
  console.log(`Cleared ${deleted.deletedCount} old candidates for school.`);

  const inserted = await Candidate.insertMany(seedCandidates);
  console.log(`Successfully seeded ${inserted.length} candidate biodatas for school: ${schoolId}`);

  await mongoose.disconnect();
}

seed().catch(console.error);
